<a href="https://colab.research.google.com/github/binhminh276/hcmc-house-price_prediction/blob/main/notebooks/06_Outliers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('processed_dataset_cleaned.csv')
df

,Diện tích,Khoảng giá,Số phòng ngủ,"Số phòng tắm, vệ sinh",Pháp lý,Nội thất,Ngày hết hạn,Mặt tiền,Gần bệnh viện,Gần chợ,Gần trường học,Cao tầng,Quy hoạch,Phường,Quận
0,54.0,8.50,3.0,4.0,Không rõ,Không rõ,18/03/2026,0,0,0,0,1,0,Phường 5,Gò Vấp
1,28.4,7.00,3.0,3.0,Sổ riêng,Nội thất cơ bản,18/03/2026,1,1,1,0,1,0,Phường 4,Quận 1
2,69.0,3.30,3.0,3.0,Sổ riêng,Không rõ,16/03/2026,1,0,1,1,1,0,Phường Long Phước,Quận 9
3,78.2,6.95,3.0,3.0,Sổ riêng,Không rõ,18/03/2026,1,0,0,0,1,0,Phường Trường Thọ,Thủ Đức
4,75.9,6.70,2.0,2.0,Sổ riêng,Không rõ,18/03/2026,1,0,0,0,0,1,Phường Linh Tây,Thủ Đức
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11323,71.0,6.90,3.0,3.0,Không rõ,Không rõ,13/03/2026,0,0,0,0,1,0,Phường 16,Gò Vấp
11324,81.1,7.15,4.0,6.0,Sổ riêng,Full nội thất,11/03/2026,0,0,1,1,0,0,Phường Thới An,Quận 1
11325,23.0,2.50,2.0,3.0,Sổ riêng,Không rõ,13/03/2026,0,1,1,0,1,1,Phường Linh Xuân,Thủ Đức
11326,100.0,18.50,4.0,3.0,Sổ riêng,Không rõ,16/03/2026,1,0,0,0,1,0,Phường 14,Phú Nhuận
11327,200.0,17.00,4.0,5.0,Sổ riêng,Full nội thất,13/03/2026,0,0,1,1,1,1,Phường Bình Hưng Hòa B,Bình Tân

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11328 entries, 0 to 11327
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Diện tích              11328 non-null  float64
 1   Khoảng giá             11328 non-null  float64
 2   Số phòng ngủ           11328 non-null  float64
 3   Số phòng tắm, vệ sinh  11328 non-null  float64
 4   Pháp lý                11328 non-null  object
 5   Nội thất               11328 non-null  object
 6   Ngày hết hạn           11328 non-null  object
 7   Mặt tiền               11328 non-null  int64
 8   Gần bệnh viện          11328 non-null  int64
 9   Gần chợ                11328 non-null  int64
 10  Gần trường học         11328 non-null  int64
 11  Cao tầng               11328 non-null  int64
 12  Quy hoạch              11328 non-null  int64
 13  Phường                 11328 non-null  object
 14  Quận                   11328 non-null  object
dtypes: float64(4), int64(6), object(5)
memory usage: 1.3+ MB

In [ ]:
df['area_per_bedroom'] = df['Diện tích'] / df['Số phòng ngủ']
df['area_per_bathroom'] = df['Diện tích'] / df['Số phòng tắm, vệ sinh']

In [ ]:
df[df['area_per_bedroom'] > 50]

,Diện tích,Khoảng giá,Số phòng ngủ,"Số phòng tắm, vệ sinh",Pháp lý,Nội thất,Ngày hết hạn,Mặt tiền,Gần bệnh viện,Gần chợ,Gần trường học,Cao tầng,Quy hoạch,Phường,Quận,area_per_bedroom,area_per_bathroom
17,250.0,7.500,4.0,4.0,Sổ riêng,Không rõ,18/03/2026,0,0,0,1,0,0,Xã An Phú Tây,Bình Chánh,62.500000,62.500
40,355.7,56.912,5.0,5.0,Sổ riêng,Không rõ,17/03/2026,0,0,0,0,1,0,Phường Thạnh Mỹ Lợi,Quận 2,71.140000,71.140
70,191.0,9.900,3.0,2.0,Sổ riêng,Không rõ,08-03-26,1,0,0,0,0,0,Phường Hiệp Bình Phước,Thủ Đức,63.666667,95.500
87,174.0,9.750,3.0,3.0,Sổ riêng,Không rõ,07-03-26,0,0,0,0,0,0,Phường Tân Phong,Quận 7,58.000000,58.000
92,58.0,4.950,1.0,1.0,Sổ riêng,Không rõ,18/03/2026,0,0,0,1,0,0,Phường 26,Bình Thạnh,58.000000,58.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11256,93.0,40.000,1.0,1.0,Không rõ,Không nội thất,13/03/2026,1,0,0,0,1,0,Phường 10,Phú Nhuận,93.000000,93.000
11280,380.0,89.000,5.0,5.0,Sổ riêng,Không rõ,13/03/2026,1,0,0,0,1,0,Phường 10,Tân Bình,76.000000,76.000
11281,275.3,14.000,4.0,4.0,Sổ riêng,Không rõ,11/03/2026,0,0,1,0,0,0,Phường Tân Thới Hiệp,Quận 1,68.825000,68.825
11289,378.0,105.000,5.0,5.0,Sổ riêng,Không rõ,13/03/2026,0,0,0,0,1,0,Phường Võ Thị Sáu,Quận 3,75.600000,75.600
11308,500.0,108.000,5.0,5.0,Sổ riêng,Full nội thất,13/03/2026,0,0,0,0,1,0,Phường Võ Thị Sáu,Quận 3,100.000000,100.000

In [ ]:
if "ID" not in df.columns:
      df.insert(0, "ID", range(1, len(df) + 1))
      print(f"Đã đánh ID thành công cho {len(df)} bản ghi!")

else:
      print("Cột ID đã tồn tại trong file.")

Đã đánh ID thành công cho 11328 bản ghi!

In [ ]:
df = df.drop(df[df['Diện tích'] > 10000].index)

In [ ]:
df = df.drop(df[df['Khoảng giá'] < 0.5].index)

In [ ]:
print("-" * 45)
print(f"BÁO CÁO LÀM SẠCH")
print("-" * 45)
print(f"Tổng số bản ghi ban đầu: {len(df)}")

df['area_per_bedroom'] = df['Diện tích'] / df['Số phòng ngủ']
df['area_per_bathroom'] = df['Diện tích'] / df['Số phòng tắm, vệ sinh']


outliers = (
    (df['Diện tích'] < 10) |
    (df['area_per_bedroom'] < 4) |
    (df['area_per_bathroom'] < 4) |
    (df['area_per_bedroom'] > 200) |
    (df['area_per_bathroom'] > 200)
)

unusual_ratio = (df['Số phòng ngủ'] / df['Số phòng tắm, vệ sinh'] > 5) | \
                (df['Số phòng tắm, vệ sinh'] / df['Số phòng ngủ'] > 5)


df = df[~outliers | unusual_ratio].copy()
print(f"Số bản ghi lỗi mật độ:   {outliers.sum()}")
print(f"Số bản ghi sạch còn lại: {len(df)}")
print("\nCơ cấu tập dữ liệu theo quy mô:")
print("-" * 45)

---------------------------------------------
BÁO CÁO LÀM SẠCH
---------------------------------------------
Tổng số bản ghi ban đầu: 11324
Số bản ghi lỗi mật độ:   84
Số bản ghi sạch còn lại: 11250

Cơ cấu tập dữ liệu theo quy mô:
---------------------------------------------

In [ ]:
df.drop('area_per_bathroom', axis = 1, inplace=True)
df.drop('area_per_bedroom', axis = 1, inplace=True)

In [ ]:
df.to_csv(
    "dataset_cleaned_outliers.csv",
    index=False,
    encoding="utf-8-sig",
    sep=";",
    decimal=",",
    float_format="%.6g"
)